In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('../data/googleplaystore_clean.csv')

In [8]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Subway Surfers,GAME,4.5,27711703,76M,1000000000,Free,0.0,Everyone 10+,Arcade,"July 12, 2018",1.90.0,4.1 and up
1,Hangouts,COMMUNICATION,4.0,3419464,Varies with device,1000000000,Free,0.0,Everyone,Communication,"July 21, 2018",Varies with device,Varies with device
2,Google,TOOLS,4.4,8021623,Varies with device,1000000000,Free,0.0,Everyone,Tools,"August 3, 2018",Varies with device,Varies with device
3,WhatsApp Messenger,COMMUNICATION,4.4,69109672,Varies with device,1000000000,Free,0.0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
4,Google News,NEWS_AND_MAGAZINES,3.9,877643,13M,1000000000,Free,0.0,Teen,News & Magazines,"August 1, 2018",5.2.0,4.4 and up

In [9]:
df.shape

(8196, 13)

In [10]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [11]:
df.columns.tolist()

['App',
 'Category',
 'Rating',
 'Reviews',
 'Size',
 'Installs',
 'Type',
 'Price',
 'Content Rating',
 'Genres',
 'Last Updated',
 'Current Ver',
 'Android Ver']

In [12]:
df.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size                  str
Installs            int64
Type                  str
Price             float64
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

In [13]:
df.describe()

            Rating       Reviews      Installs        Price
count  8196.000000  8.196000e+03  8.196000e+03  8196.000000
mean      4.173280  2.554289e+05  9.189442e+06     1.035447
std       0.536266  1.985102e+06  5.826274e+07    16.857244
min       1.000000  1.000000e+00  1.000000e+00     0.000000
25%       4.000000  1.270000e+02  1.000000e+04     0.000000
50%       4.300000  3.017000e+03  1.000000e+05     0.000000
75%       4.500000  4.397675e+04  1.000000e+06     0.000000
max       5.000000  7.812821e+07  1.000000e+09   400.000000